USE Master 
go
DROP DATABASE QLTVNEU
GO
CREATE DATABASE QLTVNEU
GO
USE QLTVNEU
GO
CREATE TABLE SINHVIEN
(
    MaSV 		CHAR(10) NOT NULL,
    TENSV 	    NVARCHAR(50),		
    NGAYSINH 	DATE,
    GIOITINH 	NVARCHAR(10),
    SDT	     	NVARCHAR(20),
    EMAIL 		VARCHAR(30),
    CONSTRAINT PK_SV PRIMARY  KEY(MASV)
)
--Tạo bảng GD :
CREATE TABLE GIAMDOC
(
    MaGD 		CHAR(10) NOT NULL,
    TENGD 		NVARCHAR(50),
    NGAYSINH 	DATE,
    GIOITINH 	VARCHAR(10), 
    SDT 	    VARCHAR(20),
    EMAIL 		VARCHAR(30),
    CONSTRAINT PK_GD PRIMARY  KEY(MAGD)
)
--Tạo bảng vị trí :
CREATE TABLE VITRI
(
    MAVT 		CHAR(10) NOT NULL,
    TENVT 		NVARCHAR(50),
    CONSTRAINT PK_VT  PRIMARY  KEY(MAVT)
)
--Tạo bảng tác giả  :
CREATE TABLE TACGIA
(
   MATG  		CHAR(10) NOT NULL,
   TENTG 		NVARCHAR(50),
   CONSTRAINT PK_TG  PRIMARY  KEY(MATG)
)
--Tạo bảng nhà xuất bản :
CREATE TABLE  NHAXUATBAN
(
    MANXB 		CHAR(10) NOT NULL,
    TENNXB 		NVARCHAR(50),
    EMAIL 		VARCHAR(50),
    DIACHI  	NVARCHAR(50),
    CONSTRAINT PK_NXB  PRIMARY  KEY(MANXB)
)
CREATE TABLE NHANVIEN(
    MaNV 		CHAR(10) NOT NULL,
    TENNV 		NVARCHAR(50),
    NGAYSINH 	DATE,
    GIOITINH 	NVARCHAR(10),
    SDT 		VARCHAR(20),
    EMAIL 		VARCHAR(30),
    MAGD 		CHAR(10) NOT NULL,
    CONSTRAINT PK_NV PRIMARY  KEY(MANV)
)
ALTER TABLE NHANVIEN  ADD CONSTRAINT fk01_NV  FOREIGN KEY(MAGD) REFERENCES GIAMDOC(MAGD)
CREATE TABLE THELOAI
(
    MATL 		CHAR(10) NOT NULL,
    TENTL 		NVARCHAR(50), 
    MAVT 		CHAR(10) NOT NULL,
    CONSTRAINT PK_TL  PRIMARY  KEY(MATL)
)
 ALTER TABLE THELOAI  ADD CONSTRAINT fk01_TL  FOREIGN KEY(MAVT) REFERENCES VITRI(MAVT)

--Tạo bảng Sach :
CREATE TABLE SACH
(
    MASACH 		CHAR(10) NOT NULL,
    TENSACH 	NVARCHAR(50),
    MATG 		CHAR(10) NOT NULL,
    MATL 		CHAR(10) NOT NULL,
    CONSTRAINT PK_S  PRIMARY  KEY(MASACH)
)
 ALTER TABLE SACH  ADD CONSTRAINT fk01_S  FOREIGN KEY(MATG) REFERENCES TACGIA(MATG)
 ALTER TABLE SACH  ADD CONSTRAINT fk02_S  FOREIGN KEY(MATL) REFERENCES THELOAI(MATL)

CREATE TABLE THEMUON
(
    MATM 		CHAR(10) NOT NULL,
    NGAYLAPTHE 	DATE,
    NGAYHETHAN 	DATE,
    MASV 		CHAR(10) NOT NULL,
    CONSTRAINT PK_TM  PRIMARY  KEY(MATM)
 )
ALTER TABLE THEMUON ADD CONSTRAINT fk01_TM  FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV)
---------------------------------------------
CREATE TABLE PHIEUMUONTRA
(
    MAPMT 		CHAR(10) NOT  NULL,
    NGAYMUON 	DATE,
    NGAYTRA 	DATE,
    MANV 		CHAR(10) NOT NULL,
    CONSTRAINT PK_PMT  PRIMARY  KEY(MAPMT)
)
 ALTER TABLE PHIEUMUONTRA  ADD CONSTRAINT fk01_PMT  FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
CREATE TABLE CAPNHATPHIEUMUONTRA(
 MAPMT	         CHAR(10),   
 MASACH          CHAR(10),
 MATM 		     CHAR(10),
 SOLUONG         NVARCHAR(10),
 THOIGIAN        DATE,
 CONSTRAINT PK_CNPMT  PRIMARY  KEY(MAPMT,MASACH,MATM)
 )
ALTER TABLE CAPNHATPHIEUMUONTRA  ADD CONSTRAINT fk01_CNPMT  FOREIGN KEY(MAPMT) REFERENCES PHIEUMUONTRA(MAPMT)
ALTER TABLE CAPNHATPHIEUMUONTRA  ADD CONSTRAINT fk02_CNPMT  FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
ALTER TABLE CAPNHATPHIEUMUONTRA  ADD CONSTRAINT fk03_CNPMT  FOREIGN KEY(MATM) REFERENCES THEMUON(MATM)


--1. Xuất danh sách thông tin nhân viên do giám đốc Lại Thu Huyền quản lý


SELECT NV.MANV,NV.TENNV,NV.SDT,NV.GIOITINH,NV.NGAYSINH 
FROM NHANVIEN NV, GIAMDOC 
WHERE  TENGD=N'Lại Thu Huyền '
AND  NV.MAGD= GIAMDOC.MAGD AND MANV IN (SELECT MANV FROM PHIEUMUONTRA)

CREATE VIEW v_danhsachnhanvien  AS
SELECT A.MANV,A.TENNV,A.SDT,A.GIOITINH,A.NGAYSINH 
FROM NHANVIEN A, GIAMDOC 
WHERE  TENGD=N'Lại Thu Huyền '
AND  A.MAGD= GIAMDOC.MAGD AND MANV 
IN (SELECT MANV FROM PHIEUMUONTRA)

--2. Thông tin sách "Vũ trụ vạn năng "  bao gồm tên thể loại, tên tác giả, vị trí 
SELECT DISTINCT  MASACH, TENSACH,TENTL, TENTG,TENVT  FROM SACH ,THELOAI,TACGIA,VITRI
 WHERE  VITRI.MAVT=THELOAI.MAVT
 AND SACH.MATL=THELOAI.MATL
 AND SACH.MATG=TACGIA.MATG
 AND TENSACH=N'Vũ trụ vạn năng'
---Create view
CREATE VIEW v_thongtinsach AS
SELECT DISTINCT  MASACH, TENSACH,TENTL, TENTG,TENVT  FROM SACH ,THELOAI,TACGIA,VITRI
 WHERE  VITRI.MAVT=THELOAI.MAVT
 AND SACH.MATL=THELOAI.MATL
 AND SACH.MATG=TACGIA.MATG
 AND TENSACH=N'Vũ trụ vạn năng'
 -- 3. Thông tin  sinh viên,ngày mượn ngày trả,SĐT 
SELECT TENSV,SDT,NGAYSINH,NGAYMUON,NGAYTRA
FROM PHIEUMUONTRA, SINHVIEN,CAPNHATPHIEUMUONTRA 
WHERE SINHVIEN.MASV=THEMUON.MASV
AND THEMUON.MATM=CAPNHATPHIEUMUONTRA.MATM   
GROUP BY TENSV,SDT,NGAYSINH,NGAYMUON,NGAYTRA
Create view
CREATE VIEW v_thongtinsinhvien AS 
SELECT  COUNT(NGAYMUON) AS 'SO LAN MUON  SACH CUA  SINHVIEN',TENSV,SDT,NGAYSINH,NGAYMUON,NGAYTRA
FROM PHIEUMUONTRA, SINHVIEN,DANGKIPHIEUMUONTRA ,CAPNHATPHIEUMUONTRA 
WHERE SINHVIEN.MASV=DANGKIPHIEUMUONTRA.MASV
AND DANGKIPHIEUMUONTRA.MAPMT =PHIEUMUONTRA.MAPMT  
GROUP BY TENSV,SDT,NGAYSINH,NGAYMUON,NGAYTRA

--8. Danh sách sách mượn 2021  bao gồm tên sách, thể loại, vị trí
SELECT MASACH,TENSACH,TENTL,TENTG,TENVT 
FROM SACH,THELOAI,TACGIA,VITRI
WHERE  VITRI.MAVT=THELOAI.MAVT
 AND SACH.MATL=THELOAI.MATL
 AND SACH.MATG=TACGIA.MATG
AND MASACH IN  
(SELECT MASACH  
 FROM CAPNHATPHIEUMUONTRA
 WHERE YEAR(THOIGIAN) =2021)

CREATE VIEW v_danhsachsachmuon2021 AS 
SELECT MASACH,TENSACH,TENTL,TENTG,TENVT 
FROM SACH,THELOAI,TACGIA,VITRI
WHERE  VITRI.MAVT=THELOAI.MAVT
       AND SACH.MATL=THELOAI.MATL
       AND SACH.MATG=TACGIA.MATG
       AND MASACH IN  
	       (SELECT MASACH  
           FROM CAPNHATPHIEUMUONTRA 
           WHERE YEAR(THOIGIAN) =2021)

