USE MASTER
GO
DROP DATABASE QUANLYXE 
GO
CREATE DATABASE QUANLYXE
GO
USE QUANLYXE
GO
-- BẢNG MẶT HÀNG
CREATE TABLE MATHANG
(
MAHANG NVARCHAR(15) PRIMARY KEY NOT NULL,
TENHANG NVARCHAR(100) ,
NHASX NVARCHAR(30),
THONGTINBH NVARCHAR(30),
SOLUONG INT,
GIA INT,
MOTA NVARCHAR(100),
)
ALTER TABLE MATHANG ALTER COLUMN GIA FLOAT;
-- BẢNG NHÀ CUNG CẤP
CREATE TABLE NHACUNGCAP(
MANCC NVARCHAR(10) PRIMARY KEY NOT NULL,
TENNCC NVARCHAR(30),
DIACHI NVARCHAR(30),
DIENTHOAI NVARCHAR(10),
EMAIL NVARCHAR(30)
)
-- BẢNG NHÂN VIÊN
CREATE TABLE NHANVIEN(
MANV NVARCHAR(10) PRIMARY KEY,
HONV NVARCHAR(10),
TENDEM NVARCHAR(20),
TENNV NVARCHAR (10),
GIOITINH NCHAR(3) CHECK(GIOITINH IN(N'NAM',N'NỮ')),
DIENTHOAI NCHAR(10),
NAMSINH INT,
DIACHI NVARCHAR(30),
LUONGCB INT,
HSLUONG FLOAT
)
-- BẢNG KHÁCH HÀNG
CREATE TABLE KKHACHHANG(
MAKH NVARCHAR(10) PRIMARY KEY,
HO NVARCHAR(10),
TENDEM NVARCHAR(20),
TENKH NVARCHAR(10),
NGAYSINH DATE,
DIACHI NVARCHAR(30),
DIENTHOAI NVARCHAR(10),
EMAIL NVARCHAR(30)
)
--BẢNG PHIẾU NHẬP
CREATE TABLE PHIEUNHAP(
MAPN NVARCHAR(10) PRIMARY KEY,
NGAYNHAP DATE,
MANV NVARCHAR(10) FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
MANCC NVARCHAR (10) FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
)
-- BẢNG PHIẾU XUẤT
CREATE TABLE PHIEUXUAT(
MAPX NVARCHAR(10) PRIMARY KEY,
NGAYXUAT DATE,
MANV NVARCHAR(10) FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
MAKH NVARCHAR (10) FOREIGN KEY (MAKH) REFERENCES KKHACHHANG(MAKH)
)
-- BẢNG CHI TIẾT PHIẾU NHẬP
CREATE TABLE CTPHIEUNHAP(
MAPN NVARCHAR (10) foreign key (MAPN) REFERENCES PHIEUNHAP(MAPN),
MAH NVARCHAR (15) FOREIGN KEY(MAH) REFERENCES MATHANG(MAHANG),
SOLUONGNHAP INT,
DONGIA INT,
THUE decimal(5,3)constraint chk_Demo_THUE check (THUE between 0 and 1),
CONSTRAINT CTPN_MAPNH_PK PRIMARY KEY (MAPN,MAH)
)
-- BẢNG CHI TIẾT PHIẾU XUẤT
CREATE TABLE CTPHIEUXUAT(
MAPX NVARCHAR (10)FOREIGN KEY (MAPX) REFERENCES PHIEUXUAT( MAPX),
MAH NVARCHAR (15)FOREIGN KEY (MAH) REFERENCES MATHANG(MAHANG),
SOLUONGXUAT INT,
DONGIA INT,
THUE decimal(5,3) constraint chk_THUE check (THUE between 0 and 1),
CONSTRAINT CTPN_MAPXH_PK PRIMARY KEY (MAPX,MAH)
)
--CÂU 1: HÀNG HÓA CÓ DOANH THU CAO NHẤT TRONG QUÝ 1 NĂM 2021
SELECT TOP 1 TENHANG, SUM(SOLUONGXUAT*DONGIA*(1+THUE)) AS "TDT"
FROM MATHANG,CTPHIEUXUAT,PHIEUXUAT
WHERE (MONTH(NGAYXUAT) BETWEEN 1 AND 3) AND YEAR(NGAYXUAT)=2021 AND
MAH=MAHANG AND PHIEUXUAT.MAPX=CTPHIEUXUAT.MAPX 
GROUP BY TENHANG
ORDER BY TDT DESC

--CÂU 2: CÓ BAO NHIÊU XE KHÔNG BÁN ĐƯỢC TRONG QUÝ 2 NĂM 2021
SELECT COUNT (MAHANG) AS "SỐ XE KHÔNG BÁN ĐƯỢC TRONG QUÝ 2"
FROM MATHANG,PHIEUXUAT,CTPHIEUXUAT
WHERE (MONTH(NGAYXUAT) BETWEEN 4 AND 6) AND MAHANG=MAH AND
PHIEUXUAT.MAPX=CTPHIEUXUAT.MAPX
AND YEAR(NGAYXUAT)=2021 
AND MAHANG NOT IN( SELECT MAH FROM CTPHIEUXUAT)
--CÂU 3: MẪU XE AIR BLADE CÓ NHỮNG MẶT HÀNG NÀO CÒN TỒN ,SL BAO NHIÊU:
SELECT CTPHIEUNHAP.MAH,TENHANG,((SOLUONG)-SUM(SOLUONGXUAT))AS TONKHO
FROM CTPHIEUNHAP,CTPHIEUXUAT,MATHANG 
WHERE MATHANG.MAHANG=CTPHIEUXUAT.MAH AND MATHANG.MAHANG=CTPHIEUNHAP.MAH 
AND TENHANG LIKE '%AIR%'
GROUP BY CTPHIEUNHAP.MAH,TENHANG,SOLUONG
--CÂU 4:ĐƯA RA LOẠI XE CÓ THÔNG TIN BẢO HÀNH TRÊN 2 NĂM CÓ SỐ LƯỢNG XE ĐÃ 
--BÁN ÍT NHẤT VÀ ĐƯA RA DOANH THU CỦA MỖI LOẠI XE 
SELECT MAHANG, TENHANG,THONGTINBH, SUM(SOLUONGXUAT) AS "LƯỢNG XE ĐÃ BÁN ",
SUM(CONVERT (BIGINT, SOLUONGXUAT*DONGIA*(1+THUE))) AS"DOANH THU "
FROM MATHANG, CTPHIEUXUAT
WHERE MAH=MAHANG AND THONGTINBH > N'2 NĂM' AND SOLUONGXUAT IN ( SELECT
MIN(SOLUONGXUAT) FROM CTPHIEUXUAT)
GROUP BY MAHANG,TENHANG, THONGTINBH
ORDER BY SUM(CONVERT (BIGINT, SOLUONGXUAT*DONGIA*(1+THUE))) DESC
--CÂU 5 ĐƯA RA THÔNG TIN CỦA 3 NHÂN VIÊN CÓ MỨC LƯƠNG CAO NHẤT 
SELECT TOP 3 MANV,(HONV + ' ' + TENDEM+ ' ' +TENNV)AS
TENCNV,NAMSINH,DIACHI,DIENTHOAI,(LUONGCB*HSLUONG) AS LUONG
FROM NHANVIEN
ORDER BY LUONG DESC
--CÂU 6: LOẠI XE NÀO ĐƯỢC MUA NHIỀU NHẤT THEO TỪNG NHÀ CUNG CẤP 
SELECT NHASX, TENHANG,SUM(SOLUONGXUAT)AS"SỐ LẦN MUA"
FROM MATHANG,CTPHIEUXUAT
WHERE MATHANG.MAHANG=CTPHIEUXUAT.MAH
AND SOLUONGXUAT IN (SELECT MAX(SOLUONGXUAT) FROM CTPHIEUXUAT)
GROUP BY NHASX,TENHANG
ORDER BY NHASX DESC
--CÂU 7:ĐƯA RA SỐ LƯỢNG HÀNG NHẬP, XUẤT, TỒN CỦA CỬA HÀNG ĐẾN THỜI ĐIỂM HIỆN TẠI 
SELECT MAHANG, TENHANG, (SOLUONGNHAP)AS "SỐ LƯỢNG NHẬP",SUM(SOLUONGXUAT)AS
"SỐ LƯỢNG XUẤT" ,((SOLUONG) -SUM(SOLUONGXUAT))AS LUONGTONKHO
FROM MATHANG,CTPHIEUNHAP ,CTPHIEUXUAT 
WHERE CTPHIEUXUAT.MAH=MATHANG.MAHANG AND CTPHIEUNHAP.MAH=MATHANG.MAHANG
GROUP BY MAHANG, TENHANG,SOLUONG,SOLUONGNHAP
ORDER BY LUONGTONKHO DESC
--CÂU 8:TỔNG TIỀN NHẬP HÀNG THEO TỪNG HÃNG XE TRONG QUÝ 1
SELECT NHASX, SUM(CONVERT (bigint,DONGIA*SOLUONGNHAP*(1+THUE)))AS "TỔNG 
TIỀN NHẬP HÀNG QUÝ 1" 
FROM CTPHIEUNHAP,PHIEUNHAP,MATHANG
WHERE CTPHIEUNHAP.MAPN=PHIEUNHAP.MAPN AND MATHANG.MAHANG=CTPHIEUNHAP.MAH
AND (MONTH(NGAYNHAP) BETWEEN 1 AND 3) AND YEAR(NGAYNHAP)=2021 
GROUP BY NHASX
--CÂU 9: NHÂN VIÊN CÓ DOANH SỐ BÁN HÀNG NHIỀU NHẤT 
SELECT NHANVIEN.MANV,(HONV + ' ' + TENDEM+ ' ' +TENNV)AS
TENCNV,NAMSINH,DIACHI,DIENTHOAI, TONGDT.DT
FROM NHANVIEN JOIN
(SELECT TOP 1 MANV,SUM(CONVERT(BIGINT,SOLUONGXUAT*DONGIA*(1+THUE)))AS
DT 
FROM CTPHIEUXUAT,PHIEUXUAT
WHERE CTPHIEUXUAT.MAPX=PHIEUXUAT.MAPX GROUP BY MANV ORDER BY DT DESC)
AS TONGDT ON TONGDT.MANV=NHANVIEN.MANV
--CÂU 10: TỔNG DOANH THU THEO TỪNG NHÀ CUNG CẤP THEO ,SỐLUONG
SELECT NHASX, SUM(CONVERT(BIGINT,DONGIA*SOLUONGXUAT*(1+THUE)))AS "TỔNG 
DOANH THU" ,SUM(SOLUONGXUAT)AS "SỐ LƯỢNG XUẤT"
FROM CTPHIEUXUAT,PHIEUXUAT,MATHANG
WHERE CTPHIEUXUAT.MAPX=PHIEUXUAT.MAPX AND MATHANG.MAHANG=CTPHIEUXUAT.MAH
GROUP BY NHASX
ORDER BY SUM(CONVERT(BIGINT,DONGIA*SOLUONGXUAT)) DESC

